<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="thingML" nsURI="http://www.thingml.org/xtext/ThingML" nsPrefix="thingML">
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readonly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="init" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Message">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sends" unique="false" upperBound="-1"
        eType="#//Message"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receives" unique="false"
        upperBound="-1" eType="#//Message"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" eType="#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exit" eType="#//Action"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internal" upperBound="-1"
        eType="#//InternalTransition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//Transition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Handler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//Event"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//Action"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//Handler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalTransition" eSuperTypes="#//Handler"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeState" eSuperTypes="#//State #//StateContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" upperBound="-1"
        eType="#//Region" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="session" upperBound="-1"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Region" eSuperTypes="#//StateContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initial" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="history" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="substate" upperBound="-1"
        eType="#//State" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReceiveMessage" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" eType="#//Message"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression"/>
</ecore:EPackage>
